"""update tables after models refactor

Revision ID: 4ffd85c2305f
Revises: 3f11049af0f8
Create Date: 2025-10-08 10:36:50.975703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffd85c2305f'
down_revision: Union[str, Sequence[str], None] = '3f11049af0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'symbol',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('assets', 'coingecko_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_index('ix_unique_portfolio_per_user_name', 'portfolios', ['user_id', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_portfolio_per_user_name', table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.alter_column('assets', 'coingecko_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('assets', 'symbol',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
